/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package totalvideogrouptimelength;

import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import java.io.File;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import uk.co.caprica.vlcj.binding.LibVlc;
import uk.co.caprica.vlcj.player.MediaPlayerFactory;
import uk.co.caprica.vlcj.player.embedded.EmbeddedMediaPlayer;
import uk.co.caprica.vlcj.player.embedded.windows.Win32FullScreenStrategy;
import uk.co.caprica.vlcj.runtime.RuntimeUtil;

/**
 *
 * @author salah
 */
public class VideoLengthTotal extends javax.swing.JFrame {

    /**
     * Creates new form VideoLengthTotal
     */
    MediaPlayerFactory mpf;
    EmbeddedMediaPlayer emp;
    final String [] videoExtensionList = {".mp4",".mkv"};
    
    boolean keepSearching=true;
    
    boolean isVideo(String name){
        try{
            name = name.substring(name.lastIndexOf("."));
            System.out.println(name);
        }catch(Exception e){
            return false;
        }
        return false;
    }
    
    
    long addMiliSec(File[]files){
        if(files == null) return 0;
        long miliSec = 0;
        String fName;
        for (File file : files) {
            if(!keepSearching)break;
            if (file.isDirectory()) {
                miliSec += addMiliSec(file.listFiles());
            } else if (file.isFile()) {
                //if(!isVideo( file.getName() ))continue;
                //the above is not needed
                try {
                    jLabel1.setText("Current File: "+file.getName());
                    fName = file.toURI().toURL().toExternalForm();
                    fName = fName.replaceFirst("/","///");
//                    System.out.println(fName);
                    emp.prepareMedia(fName);
                    emp.requestParseMedia();
                    emp.parseMedia();
                    miliSec += emp.getMediaMeta().getLength();
//                    System.out.println(miliSec);
//                    System.out.println(emp.getMediaMeta());
                }catch (MalformedURLException ex) {
                    Logger.getLogger(VideoLengthTotal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        return miliSec;
    }
        


    
    public VideoLengthTotal() {
        initComponents();
        setLocationRelativeTo(null);
        mpf=new MediaPlayerFactory();
        emp= mpf.newEmbeddedMediaPlayer(new Win32FullScreenStrategy(this));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Select Folder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(51, 0, 102));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("To calculate total length of a group of videos in a folder use \"Select Folder\" button to select one or more folder, use \"Select Multiple Files\" if you want to choose files along with the folders note that everything selected should be in the same browsing directory, do not press Enter to enter a folder press double click to go within the folder\n\nThe label below should show the current file being looked at\n\nAt anytime should you feel the search is too long and want results so far press stop search");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Select Multiple Files");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Stop Search");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Current File: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //* No errors if wrong extension
        JFileChooser fc=new JFileChooser(System.getProperty("user.home")+"/Desktop");
        fc.setDialogTitle("Choose Directory");
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //not sure about this one
        fc.setAcceptAllFileFilterUsed(false);
        fc.setMultiSelectionEnabled(true);
        JOptionPane.showMessageDialog(null,"Double click to enter to a directory,\n"
                + "pressing enter or clicking open button will select the directory");
        fc.showOpenDialog(null);
        
        File [] files = fc.getSelectedFiles();
        if(files!=null){if(files.length!=0){
            new Thread(){
                @Override
                public void run(){
                    keepSearching=true;
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    
                    jButton3.setEnabled(true);
                    long totalMiliSec=0;
                    totalMiliSec+=addMiliSec(files);

                    int seconds, mins, hrs;
                    seconds = (int) (totalMiliSec/1000); totalMiliSec%=1000;
                    mins = seconds/60; seconds %= 60;
                    hrs = mins/60; mins %= 60;
                    
                    String addT = "";
                    jLabel1.setText("Current File: ");
                    if(!keepSearching)addT="So Far ";
                    JOptionPane.showMessageDialog(null,addT+"Total time: " + hrs + ":" + mins +
                            ":" + seconds + "." + totalMiliSec);
                    keepSearching=false;
                    
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(false);
                }
            }.start();
        }}
        
        //*/

//        JOptionPane.showMessageDialog(null,""+time);
//        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        keepSearching = false;
        jButton3.setEnabled(false);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //* No errors if wrong extension
        JFileChooser fc=new JFileChooser(System.getProperty("user.home")+"/Desktop");
        //not sure about this one
        fc.setMultiSelectionEnabled(true);
        JOptionPane.showMessageDialog(null,"Double click to enter to a directory,\n"
                + "pressing enter or clicking open button will select the directory");
        fc.showOpenDialog(null);
        
        File [] files = fc.getSelectedFiles();
        if(files!=null){if(files.length!=0){
            new Thread(){
                @Override
                public void run(){
                    keepSearching=true;
                    jButton1.setEnabled(false);
                    jButton2.setEnabled(false);
                    
                    jButton3.setEnabled(true);
                    long totalMiliSec=0;
                    totalMiliSec+=addMiliSec(files);

                    int seconds, mins, hrs;
                    seconds = (int) (totalMiliSec/1000); totalMiliSec%=1000;
                    mins = seconds/60; seconds %= 60;
                    hrs = mins/60; mins %= 60;
                    
                    String addT = "";
                    if(!keepSearching)addT="So Far ";
                    JOptionPane.showMessageDialog(null,addT+"Total time: " + hrs + ":" + mins +
                            ":" + seconds + "." + totalMiliSec);
                    keepSearching=false;
                    
                    jButton1.setEnabled(true);
                    jButton2.setEnabled(true);
                    jButton3.setEnabled(false);

                }
            }.start();
        }}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VideoLengthTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VideoLengthTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VideoLengthTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VideoLengthTotal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try{
            NativeLibrary.addSearchPath(RuntimeUtil.getLibVlcLibraryName(),"C:\\Program Files\\VideoLAN\\VLC");
            Native.loadLibrary(RuntimeUtil.getLibVlcLibraryName(), LibVlc.class);
        }catch(java.lang.UnsatisfiedLinkError | Exception e){
            JOptionPane.showMessageDialog(null,"You need VLC player 64 bit installed on windows in C:\\Program Files\nfor this program to work");
            System.exit(0);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VideoLengthTotal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables


}
